config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'cars#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :cars, only:[:index, :show, :new, :create, :destroy] do
    resources :bookings, only: :create
  end
  resources :bookings, only:[:index, :show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :customer, class_name: 'User'
  belongs_to :car
  has_one :owner, through: :car
  validates :date_start, presence: { message: "You need to pick a rental start date" }
  validates :date_end, presence: { message: "You need to pick a rental end date" }

  def total_days
    ((date_end - date_start) + 1).to_i
  end

  def total_price
    ((date_end - date_start) + 1) * car.price
  end
end

# Rental from: <%= @booking.date_start  %> to: <%= @booking.date_end  %>.<br>
# Days rented: <%= ((@booking.date_end) - (@booking.date_start) + 1).to_i %> days. <br>
# Total rental price: <%= ((@booking.date_end) - (@booking.date_start) + 1) * (@booking.car.price) %> €.

app/models/car.rb
class Car < ApplicationRecord
  AUTHORIZED_FUELS = ["Gasoline", "Electric", "Diesel"]
  AUTHORIZED_GEARBOXES = ["Manual", "Automatic", "Automanual"]
  RANGE_PRICES = ["0€-10€", "10€-20€", "20€-30€",
                  "30€-40€", "40€-50€", "50€-60€",
                  "60€-70€", "70€-80€", "80€-90€",
                  "90€-100€"]
  AUTHORIZED_ADDRESS = ["Paris", "Lyon", "Grenoble", "Marseille", "Bordeaux", "Saint-Étienne", "Nice"]

  belongs_to :owner, class_name: 'User'
  has_many :bookings, dependent: :destroy
  validates :fuel, inclusion: { in: AUTHORIZED_FUELS }
  validates :gearbox, inclusion: { in: AUTHORIZED_GEARBOXES }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :customer_bookings, foreign_key: 'customer_id', class_name: 'Booking'
  has_many :owner_cars, foreign_key: 'owner_id', class_name: 'Car'
  has_many :owner_bookings, through: :owner_cars, source: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    skip_before_action :authenticate_user!, only: :home
    before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  def home
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def create
    @car = Car.find(params[:car_id])
    @booking = Booking.new(car_params)
    @booking.customer = current_user
    @booking.car = @car
    if @booking.save
      redirect_to booking_path(@booking)
    else
      @bookings       = @car.bookings
      @bookings_dates = @bookings.map do |booking|
      {
        from: booking.date_start,
        to:   booking.date_end
      }
      end
      render 'cars/show'
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def car_params
    params.require(:booking).permit(:date_start, :date_end)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
    if params[:query].present?
      sql_query = "brand ILIKE :query OR model ILIKE :query"
      @cars = Car.where(sql_query, query: "%#{params[:query]}%")
    else
      @cars = Car.all
    end

    if params[:fuel].present?
      @cars = @cars.where(fuel: params[:fuel])
    end

     if params[:gearbox].present?
      @cars = @cars.where(gearbox: params[:gearbox])
    end

    if params[:price].present?
      prices = params[:price].delete('€').split('-')
      @cars = @cars.where("price > #{prices.first.to_f} AND price < #{prices.last.to_f}")
    end

    if params[:address].present?
      @cars = @cars.where(address: params[:address])
    end


    @markers = @cars.geocoded.map do |car|
      {
        lat: car.latitude,
        lng: car.longitude,
        info_window: render_to_string(partial: "info_window", locals: { car: car }),
        image_url: helpers.asset_url('car.png')
      }
    end
  end

  def show
    @car = Car.find(params[:id])
    @booking = Booking.new
    @markers = [{
      lat: @car.latitude,
      lng: @car.longitude,
      info_window: render_to_string(partial: "info_window", locals: { car: @car }),
      image_url: helpers.asset_url('car.png')
    }]

    @bookings       = @car.bookings
    @bookings_dates = @bookings.map do |booking|
      {
        from: booking.date_start,
        to:   booking.date_end
      }
    end
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.owner = current_user
    if @car.save
      redirect_to car_path(@car)
    else
      render :new
    end
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to cars_path
  end

  private

  def car_params
    params.require(:car).permit(:brand, :model, :fuel, :price, :gearbox, :owner, :photo_url)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :date_start, label: 'From :' placeholder: 'DD/MM/YYYY' %>
  <%= f.input :date_end:, label: 'To' placeholder: 'DD/MM/YYYY' %>

  <%= f.button :submit %>
<% end %>

app/views/bookings/index.html.erb
<div class="list">
  <% @bookings.each do |booking| %>
    <div class="contenu">
      <div class="contenu_image">
        <img src="https://images.unsplash.com/photo-1507136566006-cfc505b114fc?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=963&q=80" />
      </div>
      <div class="contenu_title contenu-container">
        <div class="brand"><p><%= booking.car.brand %></p></div>
        <div class="model"><p><%= booking.car.model %></p></div>
        <div class="dollar"><p><%= booking.car.price() %>€</p></div>
        <div class="booking-button">
          <%= link_to "Book Now", booking_path(:id => booking.id), :class => "btn btn-warning book" %>
        </div>
      </div>
    </div>
  <%end%>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <div class="card m-1 mx-auto" style="width: 30rem;">

    <img src="<%= @booking.car.photo_url %>" class="card-img-top" alt="...">

    <div class="card-body bg-dark text-white">

      <div class="d-flex justify-content-between">
        <h5 class="card-title text-uppercase font-weight-bold"><%= @booking.car.brand %></h5>
        <h5 class="card-title text-uppercase font-weight-bold"><%= @booking.car.model %></h5>
      </div>

      <div>
        <hr>
          <p class="card-title text-center">From:   <%= @booking.date_start %>
          To:   <%= @booking.date_end %></p>
          <p class="text-center">Number of days:   <%= @booking.total_days() %></p>
          <p class="text-center">Total price:   <%= @booking.total_price() %>€</p>
      </div>


      <div class='mx-auto w-100'>
          <%= link_to "Go back to my bookings", bookings_path, :class => "w-100 mx-auto mb-3 btn btn-warning" %>
          <%= link_to "Cancel this booking", booking_path(@booking), method: :delete, :class => "mx-auto btn btn-warning", data: { confirm: "Are you sure you want to cancel this booking?"}, class: 'w-100 btn btn-warning'  %>
      </div>

    </div>

  </div>

</div>

app/views/cars/_info_window.html.erb
<h2><%= car.name %></h2>
<p><%= car.address %></p>

app/views/cars/index.html.erb
<div class='top-text'>
  <h1><span>What will today's<span style='color: #E67E22; padding: 0px'>car</span>be?</span></h1>
</div>
<div class='row'>
  <div class='searchbar col-3'>
    <div class='position-fixed ml-4' style='width: 22%'>
      <%= simple_form_for :search, method: :get,
        html: { class: 'bg-dark rounded-lg p-3 d-flex align-middle flex-column' } do |f| %>
        <%= f.input :query, placeholder: "Find a car...",
                            label: false,
                            input_html: { name: :query,
                                          value: params.dig(:query) } %>


        <%= f.input :gearbox, collection: Car::AUTHORIZED_GEARBOXES,
                          selected: params.dig(:gearbox),
                          include_blank: "- Select Gearbox -",
                          label: false,
                          input_html: { name: :gearbox } %>

        <%= f.input :fuel, collection: Car::AUTHORIZED_FUELS,
                          selected: params.dig(:fuel),
                          include_blank: "- Select fuel -",
                          label: false,
                          input_html: { name: :fuel } %>

        <%= f.input :price, collection: Car::RANGE_PRICES,
                          selected: params.dig(:price),
                          include_blank: "- Select price -",
                          label: false,
                          input_html: { name: :price } %>

        <%= f.input :address, collection: Car::AUTHORIZED_ADDRESS,
                          selected: params.dig(:address),
                          include_blank: "- Select address -",
                          label: false,
                          input_html: { name: :address } %>

        <div class='rounded-lg'>
          <%= f.submit "Search", class: "text-center btn btn-warning btn-block"  %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="container col-8">
    <div class="grid-container">
      <% @cars.each do |car| %>

        <div class="car-card">

          <div class="car-card-photo">
            <img src="<%= car.photo_url %>" class="card-img-top card-car-photos" alt="...">
          </div>

          <div class="car-car-body">
            <div class="d-flex justify-content-between mb-4">
              <div class="car-card-brand">
                <%= car.brand %>
              </div>
              <div class="car-card-model">
                <%= car.model %>
              </div>
            </div>
            <div class="car-card-details">
              <div><strong>Fuel: </strong><%= car.fuel %></div><div><strong>Gearbox: </strong> <%= car.gearbox %></div>
            </div>
            <div class="car-card-bottom">
              <div class="car-card-price"><%= car.price %> €/day</div>
              <div class="car-card-button"><%= link_to "Rent me!", car_path(:id => car.id) %></div>
            </div>
          </div>
        </div>
      <%end%>
    </div>
  </div>


  <div class="col">
  </div>

</div>

app/views/cars/new.html.erb
<div class='row'>
  <div class='container bg-dark p-3 col-6'>
    <%= simple_form_for @car do |f| %>
      <%= f.input :brand, placeholder: 'car brand', error: 'Brand is mandatory, please specify one' %>
      <%= f.input :model, placeholder: 'car model', error: 'Model is mandatory, please specify one' %>
      Fuel<%=f.input :fuel, collection: Car::AUTHORIZED_FUELS,
                              selected: params.dig(:fuel),
                              include_blank: "- Select fuel -",
                              label: false,
                              error: 'Fuel is mandatory, please specify one' %>
      Gearbox<%= f.input :gearbox, collection: Car::AUTHORIZED_GEARBOXES,
                          selected: params.dig(:gearbox),
                          include_blank: "- Select Gearbox -",
                          label: false,
                          error: 'Gearbox type is mandatory, please specify one' %>
      <%= f.input :address, placeholder: 'car location', error: 'A location is mandatory, please specify one' %>
      <%= f.input :price, placeholder: 'price per day', error: 'Price is mandatory, please specify one' %>
      <%= f.input :photo_url, placeholder: 'car photo URL', error: 'A photo is mandatory, please upload one' %>
      <div class='mx-auto w-100'>
        <%= f.button :submit, 'add car', class: 'w-100 mx-auto btn btn-warning' %>
      </div>
    <% end %>
  </div>
</div>

app/views/cars/show.html.erb
<div class='container'>

  <div class="car-container">


  <!-- separation  -->

    <div class='ml-3 p-3'>

      <div>
        <img src="<%= @car.photo_url %>" width= 600px alt="">
      </div>

      <div class='ml-3 font-weight-bold pt-3'>
        <%= @car.brand %> <%= @car.model %>
      </div>

      <div class='ml-3'>
        <%= @car.fuel %>
      </div>


      <div class='ml-3'>
        <%= @car.gearbox %>
      </div>

      <div class='ml-3'>
        <%= @car.address %>
      </div>

      <div class='ml-3'>
        <h2><%= @car.price %> € / Day</h2>
      </div>
    </div>
      <div class='mx-auto'>

        <div id="booking-form-div" data-bookings="<%= @bookings_dates.to_json %>"></div>
          <div>
            <%= simple_form_for [@car, @booking] do |f| %>
              <%= f.input :date_start, label: "Select the rental dates", as: :string, required: true, input_html: {id: "range_start", class: "font-weight-bold d-none"} %>
              <%= f.input :date_end, class: 'font-weight-bold', label: false , as: :string, required: true, input_html: {id: "range_end", class: "d-none"} %>
              <%= f.button :submit, class: 'w-100 mx-auto btn btn-warning'%>
            <% end %>
          </div>
        </div>

      </div>


    </div>

  <div class='mx-auto w-75'>
    <div id="map"
      style="width: 100%; height: 600px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carnage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

    <%= render 'shared/footer' %>


  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<p> hello <%= current_user.email %></p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-dark">
  <p>Directed by @leogenuit - @nicolasfeuerstein - @thithuhanguyen</p>
  <p>©carnage 2021</p>
  <div class="d-flex justify-content-center pt-3">
    <i class="fab fa-facebook"></i>
    <i class="fab fa-twitter"></i>
    <i class="fab fa-instagram"></i>
    <i class="fab fa-snapchat"></i>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class='sticky-top'>
  <div class="navbar navbar-expand-sm navbar-dark bg-dark navbar-lewagon">
    <%= link_to "/cars", class: "navbar-brand" do %>

      <%= image_tag "https://i.ibb.co/J2VBTWd/flat-vintage-car-icon-600568-2.png" %> <span class="text-warning">CAR</span>NAGE

      <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Browse cars", cars_path, :class => "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Lease my car", new_car_path, :class => "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My bookings", bookings_path, :class => "nav-link" %>
          </li>
          <li class="nav-item ">
            <%= link_to "Logout",  destroy_user_session_path, method: :delete, :class => "nav-link" %>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class='bg-warning' style='height:4px'></div>
</div>